---
title: "R Notebook"
output: html_notebook
---

**Tidyverse**

```{r}
library('tidyverse')
```

```{r}
mpg
```

```{r}
iris
```

```{r}
dplyr::filter(mpg, model == 'a4')
```

```{r}
mpg %>%
  dplyr::filter(model == 'a4')
```

```{r}
mpg %>%
  dplyr::filter(model == 'a4') %>%
  dplyr::arrange(displ, cyl)
```

```{r}
mpg %>%
  dplyr::filter(model == 'a4') %>%
  dplyr::arrange(displ, cyl) %>%
  dplyr::mutate(old = year < 2000)
```

```{r}
mpg %>%
  dplyr::filter(model == 'a4') %>%
  dplyr::arrange(displ, cyl) %>%
  dplyr::mutate(old = year <2000) %>% 
  dplyr::transmute(full_wheel_drive = drv == 'f')
```

```{r}
mpg %>%
  dplyr::filter(model == 'a4') %>%
  dplyr::arrange(displ, cyl) %>%
  dplyr::mutate(old = year <2000, fwd = drv == 'f')
```

```{r}
mpg %>%
  dplyr::filter(model == 'a4') %>%
  dplyr::arrange(displ, cyl) %>%
  dplyr::mutate(old = year <2000, fwd = drv == 'f') %>% 
  dplyr::select(-drv)
```

```{r}
mpg %>%
  dplyr::count()
```

```{r}
mpg %>%
  dplyr::count(model, sort = TRUE)
```

```{r}
head(mpg)
```

```{r}
mpg[mpg$model == 'a4',]
```

```{r}
c(1:10)
```

```{r}
tibble(x = 1:3, y = list(1:5, 1:10, 1:20))
```

```{r}
as_tibble(mpg)
```

```{r}
class(mpg)
```

```{r}
x <- as_tibble(iris)
```

```{r}
length(x)
```

```{r}
x
```

```{r}
y <- tibble(
  x = 1:5, 
  y = 1, 
  z = x ^ 2 + y
)
```

```{r}
y
```

```{r}
y$z
```

```{r}
runif(5)
```

```{r}
rnorm(5)
```

```{r}
y %>% .$x
```

```{r}
mpg
```

```{r}
mpg %>% .$model
```

```{r}
as_data_frame(mpg)
```

```{r}
filter(mpg, model == 'a4')
```

```{r}
mpg %>% 
  filter(model == 'a4')
```

```{r}
df <- read_csv('avengers.csv')
```

```{r}
df
```

```{r}
?pirates
```

```{r}
install.packages('yarrr')
```

```{r}
require('yarrr')
```

```{r}
?pirates
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
